# 1. KẾT NỐI BẰNG WINDOWS AUTHENTICATION (Theo ảnh chụp của bạn)
# Lưu ý: Không cần spring.datasource.username và password vì đã có integratedSecurity=true
spring.datasource.url=jdbc:sqlserver://DESKTOP-OSPS4V4:1433;databaseName=QuanLiSport;integratedSecurity=true;encrypt=true;trustServerCertificate=true;
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. CẤU HÌNH HIBERNATE (Giữ nguyên cấu trúc bảng đã tạo)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. CỔNG CHẠY BACKEND
server.port=8080